name: Auto Pull

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜 12 点执行

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/DIYgod/RSSHub.git

      - name: Pull latest changes
        run: |
          git config --local user.email "1402394430@qq.com"
          git config --local user.name "zjtie"
          git fetch upstream
          git pull upstream master
          git push origin master
